### PR TITLE
(fix) Update maximum brightness cap

### PR DESCRIPTION
**Pull request by joshgoebel**
- Bump maximum brightness to 1000

I'm using an Apple Cinema 27" DisplayPort (not Thunderbolt) and my maximum brightness is 1000.

### CODE REVIEW

**Comment by joshgoebel** [comment]
Are the maintainer now?  I just wondered why Arch AUR has you pinned via the original since you are a fork...

**Comment by jenrik** [comment]
The change you are making is gonna affect all models, have you considered whether it's gonna break for other models?

The reason AUR is pointing to this repository is because I previously maintained the AUR package.

**Comment by jenrik** [comment]
I looked over the code and found that it doesn't seem to cap the value when settings the brightness non-relatively. I guess the change is fine then.

**Comment by joshgoebel** [comment]
Yeah and to do it otherwise you'd need a database per model or something, which seems no fun.  

Or you could pass the max on the command line and let people figure it out on their own.  Since you already have to manually pass the device ID. 

I'd -assume- the hardware would likely cap it itself, so I'd be curious if the cap is necessary at all. But I didn't go back and find the history of adding the limit. 

Surely it wasn't just added preemptively?

Thanks for merging. We can see how it goes.

**Pull request merged**
